### ISSUE TITLE
[nuxt] document is not defined

### ISSUE THREAD

**Issue by ArthurSegato** [johannschopplich/unlazy#30]
### Reproduction

Repo: https://github.com/ArthurSegato/portfolio-frontend
Node v20.5.0
PNPM 8.7.4
Nuxt 3.7.2
Nitro 2.6.3
Unlazy 0.10.1

![image](https://github.com/johannschopplich/unlazy/assets/19919287/5137f7e2-c26a-4717-8271-9a4870411c0c)
![image](https://github.com/johannschopplich/unlazy/assets/19919287/02a1e8d0-da37-4f7c-ade0-d4c406bf62cc)

### Describe the bug

I have a dynamic project page on my frontend that is accessible via the index page, the project page consumes images from my backend (served statically) and project data (consumed via a REST request), when accessing the project page via the home page, no error occurs, but when refreshing the page the following error appears

```javascript
500
document is not defined
at Module.lazyLoad (/C:/Users/segato/Documents/Github/portfolio-frontend/node_modules/.pnpm/@unlazy+core@0.10.1/node_modules/@unlazy/core/dist/index.mjs:14:23)
at setup (C:\Users\segato\Documents\Github\portfolio-frontend\pages\projects\[id].js:19:27)
at _sfc_main.setup (C:\Users\segato\Documents\Github\portfolio-frontend\pages\projects\[id].js:248:23)
at callWithErrorHandling (C:\Users\segato\Documents\Github\portfolio-frontend\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:156:18)
at setupStatefulComponent (C:\Users\segato\Documents\Github\portfolio-frontend\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7190:25)
at setupComponent (C:\Users\segato\Documents\Github\portfolio-frontend\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7151:36)
at renderComponentVNode (C:\Users\segato\Documents\Github\portfolio-frontend\node_modules\.pnpm\@vue+server-renderer@3.3.4_vue@3.3.4\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:614:15)
at renderVNode (C:\Users\segato\Documents\Github\portfolio-frontend\node_modules\.pnpm\@vue+server-renderer@3.3.4_vue@3.3.4\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:743:14)
at renderComponentSubTree (C:\Users\segato\Documents\Github\portfolio-frontend\node_modules\.pnpm\@vue+server-renderer@3.3.4_vue@3.3.4\node_modules\@vue\server-renderer
```

![image](https://github.com/johannschopplich/unlazy/assets/19919287/1b8a8ff4-f367-4018-810d-8f78f390d85e)

### Additional context

The error only appears when the 'lazyLoad()' function is added to the code

**Comment by johannschopplich** [comment]
If you're using Nuxt, why not use the [`@unlazy/nuxt`](https://unlazy.byjohann.dev/integrations/nuxt.html) package directly? It is SSR-ready and provides an easy-to-use `UnLazyImage` component.

If you insist on using the native unlazy `lazyLoad` function, you have to wrap your call in a `process.client` if-statement.

**Comment by ArthurSegato** [comment]
I see, I followed the documentation on the [nuxt modules page](https://nuxt.com/modules/unlazy), which appears to be out of date, thank you very much for your help!

![image](https://github.com/johannschopplich/unlazy/assets/19919287/2fe4b11c-0488-43b2-8f7c-f4ad278a07a0)

**Comment by johannschopplich** [comment]
Oh, I see. The docs are up-to-date, but since unlazy is monorepo, the Nuxt modules page fetches only the top-level README.
